name: Trigger release
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release version (with sufix)
        default: 1.0.0.Final
        required: true
      next-version:
        description: Next version (without sufix)
        default: 1.0.1
        required: true
jobs:
  release-version:
    name: Create git tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@b9cc6eabf7e7e3889766b5cee486f874c9e1bd2d
        with:
          java-version: 11
      - name: Setup git
        run: |
          git config user.name "Carlos Feria"
          git config user.email "<carlosthe19916@gmail.com>"
      - name: Prepare release
        run: |
          mvn versions:set -DnewVersion="${{ github.event.inputs.release-version }}"
          git add .
          git commit -m "Prepare release ${{ github.event.inputs.release-version }}"
          git push https://${{ secrets.RELEASE_GITHUB_TOKEN }}@github.com/project-openubl/xsender-server.git
      - name: Create tag
        run: |
          git tag "${{ github.event.inputs.release-version }}"
          git push https://${{ secrets.RELEASE_GITHUB_TOKEN }}@github.com/project-openubl/xsender-server.git --tags
      - name: Prepare next version
        run: |
          mvn versions:set -DnewVersion="${{ github.event.inputs.next-version }}-SNAPSHOT"
          git add .
          git commit -m "Prepare next release ${{ github.event.inputs.next-version }}-SNAPSHOT"
          git push https://${{ secrets.RELEASE_GITHUB_TOKEN }}@github.com/project-openubl/xsender-server.git
